/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachAccessRouteImport } from './routes/coach-access'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InfoRouteImport } from './routes/info'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MysafaRouteImport } from './routes/mysafa'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachIdRouteImport } from './routes/coach.$id'
import { Route as LeaguesIndexRouteImport } from './routes/leagues.index'
import { Route as LeaguesSlugRouteImport } from './routes/leagues.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAccessRoute = CoachAccessRouteImport.update({
  id: '/coach-access',
  path: '/coach-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MysafaRoute = MysafaRouteImport.update({
  id: '/mysafa',
  path: '/mysafa',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIdRoute = CoachIdRouteImport.update({
  id: '/coach/$id',
  path: '/coach/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/leagues/$slug',
  path: '/leagues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach-access': typeof CoachAccessRoute
  '/fixtures': typeof FixturesRoute
  '/history': typeof HistoryRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/mysafa': typeof MysafaRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/coach/$id': typeof CoachIdRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach-access': typeof CoachAccessRoute
  '/fixtures': typeof FixturesRoute
  '/history': typeof HistoryRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/mysafa': typeof MysafaRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/coach/$id': typeof CoachIdRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/coach': typeof CoachIndexRoute
  '/leagues': typeof LeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach-access': typeof CoachAccessRoute
  '/fixtures': typeof FixturesRoute
  '/history': typeof HistoryRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/mysafa': typeof MysafaRoute
  '/notifications': typeof NotificationsRoute
  '/pending': typeof PendingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/coach/$id': typeof CoachIdRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach-access'
    | '/fixtures'
    | '/history'
    | '/info'
    | '/login'
    | '/mysafa'
    | '/notifications'
    | '/pending'
    | '/player'
    | '/profile'
    | '/register'
    | '/sponsors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/coach/$id'
    | '/leagues/$slug'
    | '/admin/'
    | '/coach/'
    | '/leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach-access'
    | '/fixtures'
    | '/history'
    | '/info'
    | '/login'
    | '/mysafa'
    | '/notifications'
    | '/pending'
    | '/player'
    | '/profile'
    | '/register'
    | '/sponsors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/coach/$id'
    | '/leagues/$slug'
    | '/admin'
    | '/coach'
    | '/leagues'
  id:
    | '__root__'
    | '/'
    | '/coach-access'
    | '/fixtures'
    | '/history'
    | '/info'
    | '/login'
    | '/mysafa'
    | '/notifications'
    | '/pending'
    | '/player'
    | '/profile'
    | '/register'
    | '/sponsors'
    | '/admin/notifications'
    | '/admin/payments'
    | '/coach/$id'
    | '/leagues/$slug'
    | '/admin/'
    | '/coach/'
    | '/leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachAccessRoute: typeof CoachAccessRoute
  FixturesRoute: typeof FixturesRoute
  HistoryRoute: typeof HistoryRoute
  InfoRoute: typeof InfoRoute
  LoginRoute: typeof LoginRoute
  MysafaRoute: typeof MysafaRoute
  NotificationsRoute: typeof NotificationsRoute
  PendingRoute: typeof PendingRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SponsorsRoute: typeof SponsorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  CoachIdRoute: typeof CoachIdRoute
  LeaguesSlugRoute: typeof LeaguesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-access': {
      id: '/coach-access'
      path: '/coach-access'
      fullPath: '/coach-access'
      preLoaderRoute: typeof CoachAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysafa': {
      id: '/mysafa'
      path: '/mysafa'
      fullPath: '/mysafa'
      preLoaderRoute: typeof MysafaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$id': {
      id: '/coach/$id'
      path: '/coach/$id'
      fullPath: '/coach/$id'
      preLoaderRoute: typeof CoachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachAccessRoute: CoachAccessRoute,
  FixturesRoute: FixturesRoute,
  HistoryRoute: HistoryRoute,
  InfoRoute: InfoRoute,
  LoginRoute: LoginRoute,
  MysafaRoute: MysafaRoute,
  NotificationsRoute: NotificationsRoute,
  PendingRoute: PendingRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SponsorsRoute: SponsorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  CoachIdRoute: CoachIdRoute,
  LeaguesSlugRoute: LeaguesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
